export const appImages = {
  discover: {
    albums: {
      drake: require("./discover/albums/drake.jpg"),
      lover: require("./discover/albums/lover.jpg"),
      morganWallen: require("./discover/albums/morganWallen.jpg"),
      noah: require("./discover/albums/noah.jpg"),
      olivia: require("./discover/albums/olivia.jpg"),
      rodWave: require("./discover/albums/rodWave.jpg"),
      sza: require("./discover/albums/sza.jpg"),
      taylor: require("./discover/albums/taylor.jpg"),
      travisScott: require("./discover/albums/travisScott.jpg"),
      zachBryan: require("./discover/albums/zachBryan.jpg"),
    },
    reviews: {
      billieEilish: require("./discover/reviews/billieEilish.jpg"),
      coldplay: require("./discover/reviews/coldplay.jpg"),
      europe: require("./discover/reviews/europe.jpg"),
      linkinPark: require("./discover/reviews/linkinPark.jpg"),
      tws: require("./discover/reviews/tws.jpg"),
    },
    screen: {
      gramophone: require("./discover/gramophone.png"),
      new: require("./discover/new.png"),
    },
    songs: {
      badIdeaRight: require("./discover/songs/badIdeaRight.jpg"),
      calmDown: require("./discover/songs/calmDown.jpg"),
      cruelSummer: require("./discover/songs/cruelSummer.jpg"),
      daylight: require("./discover/songs/daylight.jpg"),
      dualipa: require("./discover/songs/dualipa.jpg"),
      greedy: require("./discover/songs/greedy.jpg"),
      red: require("./discover/songs/red.jpg"),
      singleSoon: require("./discover/songs/singleSoon.jpg"),
      vampire: require("./discover/songs/vampire.jpg"),
      wiwmf: require("./discover/songs/wiwmf.jpg"),
    },
  },
  friends: {
    damage: require("./friends/damage.jpg"),
    digo: require("./friends/digo.jpg"),
    miguel: require("./friends/miguel.jpg"),
    rian: require("./friends/rian.jpg"),
    vitor: require("./friends/vitor.jpg"),
  },
  grammy: {
    album: {
      butHereWeAre: require("./grammy/album/butHereWeAre.jpg"),
      guts: require("./grammy/album/guts.jpg"),
      midnights: require("./grammy/album/midnights.jpg"),
      sos: require("./grammy/album/sos.jpg"),
      worldMusicRadio: require("./grammy/album/worldMusicRadio.jpg"),
    },
    gravacao: {
      antiHero: require("./grammy/gravacao/anti-hero.png"),
      flowers: require("./grammy/gravacao/flowers.jpg"),
      killBill: require("./grammy/gravacao/killBill.jpg"),
      vampire: require("./grammy/gravacao/vampire.jpg"),
      wwimf: require("./grammy/gravacao/wwimf.jpg"),
    },
    musica: {
      antiHero: require("./grammy/musica/anti-hero.png"),
      aw: require("./grammy/musica/aw.jpg"),
      flowers: require("./grammy/musica/flowers.jpg"),
      killBill: require("./grammy/musica/killBill.jpg"),
      vampire: require("./grammy/musica/vampire.jpg"),
    },
  },
  home: {
    notStarted: {
      ajr: require("./home/notStarted/ajr.jpg"),
      billie: require("./home/notStarted/billie.jpg"),
      blackpink: require("./home/notStarted/blackpink.jpg"),
      cage: require("./home/notStarted/cage.jpg"),
      conan: require("./home/notStarted/conan.jpg"),
      ed: require("./home/notStarted/ed.jpg"),
      lover: require("./home/notStarted/lover.jpg"),
      shawn: require("./home/notStarted/shawn.jpg"),
      weeknd: require("./home/notStarted/weeknd.jpg"),
    },
    started: {
      adele: require("./home/started/adele.jpg"),
      badbunny: require("./home/started/badbunny.jpg"),
      beyonce: require("./home/started/beyonce.jpg"),
      coldplay: require("./home/started/coldplay.jpg"),
      harry: require("./home/started/harry.jpg"),
      justin: require("./home/started/justin.jpg"),
      lilnas: require("./home/started/lilnas.jpg"),
      taylor: require("./home/started/taylor.jpg"),
    },
  },
  profile: {
    favoriteAlbums: {
      blurryface: require("./profile/favoriteAlbums/blurryface.jpg"),
      trench: require("./profile/favoriteAlbums/trench.jpg"),
      wwafawdwg: require("./profile/favoriteAlbums/wwafawdwg.jpg"),
    },
    favoriteSongs: {
      heatWaves: require("./profile/favoriteSongs/heatWaves.jpg"),
      invisible: require("./profile/favoriteSongs/invisible.jpg"),
      levelOfConcern: require("./profile/favoriteSongs/levelOfConcern.jpg"),
      monster: require("./profile/favoriteSongs/monster.jpg"),
      oceanEyes: require("./profile/favoriteSongs/oceanEyes.jpg"),
      onlyForAMoment: require("./profile/favoriteSongs/onlyForAMoment.jpg"),
      runaway: require("./profile/favoriteSongs/runaway.jpg"),
      starboy: require("./profile/favoriteSongs/starboy.jpg"),
      theFall: require("./profile/favoriteSongs/theFall.jpg"),
      whenThePartyIsOver: require("./profile/favoriteSongs/whenThePartyIsOver.jpg"),
    },
    lastAlbumsReviews: {
      guts: require("./profile/lastAlbumsReviews/guts.jpg"),
      happierThanEver: require("./profile/lastAlbumsReviews/happierThanEver.jpg"),
      scaledAndIcy: require("./profile/lastAlbumsReviews/scaledAndIcy.jpg"),
    },
    lastSongsReviews: {
      badIdeaRight: require("./profile/lastSongsReviews/badIdeaRight.jpg"),
      calmDown: require("./profile/lastSongsReviews/calmDown.jpg"),
      daylight: require("./profile/lastSongsReviews/daylight.jpg"),
      greedy: require("./profile/lastSongsReviews/greedy.jpg"),
      lost: require("./profile/lastSongsReviews/lost.jpg"),
      singleSoon: require("./profile/lastSongsReviews/singleSoon.jpg"),
      vampire: require("./profile/lastSongsReviews/vampire.jpg"),
      voceVaiLembrarDeMim: require("./profile/lastSongsReviews/voceVaiLembrarDeMim.jpg"),
      whatWasIMadeFor: require("./profile/lastSongsReviews/whatWasIMadeFor.jpg"),
      whereSheGoes: require("./profile/lastSongsReviews/whereSheGoes.jpg"),
    },
    screen: {
      bruno: require("./profile/bruno.jpg"),
    },
  },
  screen: {
    adaptiveIcon: require("./icon.png"),
    appleMusic: require("./appleMusic.png"),
    favicon: require("./favicon.png"),
    icon: require("./icon.png"),
    login: require("./login.png"),
    splash: require("./splash.png"),
    spotify: require("./spotify.png"),
  },
  shows: {
    friendsReviews: {
      coldplay: require("./shows/friendsReviews/coldplay.jpg"),
      kiss: require("./shows/friendsReviews/kiss.jpg"),
      lolla: require("./shows/friendsReviews/lolla.jpg"),
    },
    showsBrasil: {
      evanescence: require("./shows/showsBrasil/evanescence.jpg"),
      paulMcCartney: require("./shows/showsBrasil/paulMcCartney.jpg"),
      taylorSwift: require("./shows/showsBrasil/taylorSwift.png"),
    },
    showsPOA: {
      capitalInicial: require("./shows/showsPOA/capitalInicial.jpg"),
      nxZero: require("./shows/showsPOA/nxZero.jpg"),
      rhcp: require("./shows/showsPOA/rhcp.jpg"),
    },
  },
};
